classdef GlobalHawk
    
    % -------- Global Hawk -------- 
    % Contains geometric and mass properties, FC and stability derivatives
    % of a Global Hawk airplane.
    % Exercise 1 condition.

    properties
        
        % Name [str]
        name = 'Global Hawk'
        
        % Geometric [float]
        Sw   = 48.68  % [m^2]
        c    = 1.48   % [m]
        b    = 35.42  % [m]
        
        % Mass [float]
        m    = 9375   % [kg]
        Ixb  = 168907 % [kg*m^2]
        Iyb  = 45466  % [kg*m^2]
        Izb  = 210513 % [kg*m^2]
        Ixzb = -1660  % [kg*m^2]
        
        % Flight condition [struct]
        FC = struct('hs', Utils.ft_to_m(10000),...
                    'us', Utils.kt_to_ms(320),...
                    'alphabs', Utils.deg_to_rad(0),...
                    'CLs',  0.154,...
                    'CDs',  0.026,...
                    'CTs',  0.026/cos(Utils.deg_to_rad(0)),... % Assumed equal to CDs (alpha = 0)
                    'Cms',  0,...     % Assumed 0
                    'CmTs', 0,...     % Assumed 0
                    'epss', Utils.deg_to_rad(0))
                
        % Non-dimensional derivatives [struct]
        % Longitudinal
        CD = struct('u', 0.053,...
                    'alpha', 0.036,...
                    'deltae', 0.022)
                
        CL = struct('u', 0.213,...
                    'alpha', 6.578,...
                    'alphadot', 0.463,...
                    'q', 9.031,...
                    'deltae', 0.161)
                
        CT = struct('u', -0.051,...
                    'alpha', 0)
        
        Cm = struct('u', 0.063,...
                    'Tu', 0.044,...
                    'alpha', -2.701,...
                    'alphadot', -1.900,...
                    'q', -13.777,...
                    'T', 0,...
                    'deltae', -0.661)
                
        % Lateral-directional
        CY = struct('beta', -0.296,...
                    'p', 0,...
                    'r', 0.088,...
                    'deltaa', 0,...
                    'deltar', -0.117)
                
        Cl = struct('beta', -0.022,...
                    'p', -0.567,...
                    'r', 0.056,...
                    'deltaa', 0.262,...
                    'deltar', -0.004)
                
        Cn = struct('beta', 0.007,...
                    'p', -0.022,...
                    'Tbeta', 0,...
                    'r', -0.018,...
                    'deltaa', -0.001,...
                    'deltar', 0.020)
                
    end
end

