classdef Learjet24
    
    % -------- Learjet 24 ---------
    % Contains geometric and mass properties, FC and stability derivatives
    % of a Learjet 24 airplane at cruise condition.
    % Extracted from Leyes de Control de Vuelo Appendix B.

    properties
        
        % Name [str]
        name = 'Learjet 24'
        
        % Geometric [float]
        Sw   = Utils.ft_to_m(Utils.ft_to_m(230))   % [m^2]
        c    = Utils.ft_to_m(7.0)                  % [m]
        b    = Utils.ft_to_m(34.0)                 % [m]
        
        % Mass [float]
        m    = Utils.lb_to_kg(13000)       % [kg]
        Ixb  = Utils.slgft2_tokgm2(28000)  % [kg*m^2]
        Iyb  = Utils.slgft2_tokgm2(18800)  % [kg*m^2]
        Izb  = Utils.slgft2_tokgm2(47000)  % [kg*m^2]
        Ixzb = Utils.slgft2_tokgm2(1300)   % [kg*m^2]
         
        % Flight condition [struct]
        FC = struct('hs', Utils.ft_to_m(40000),...
                    'us', Utils.ft_to_m(677),...   % Speed given in ft/s
                    'alphabs', Utils.deg_to_rad(2.7),...
                    'CLs',   0.410,...
                    'CDs',   0.0335,...
                    'CTs',  0.0335/cos(Utils.deg_to_rad(0)),...  % CTxs = CDs
                    'Cms',   0,...      
                    'CmTs',  0,...      
                    'epss',  Utils.deg_to_rad(0))
                
        % Non-dimensional derivatives [struct]
        % Longitudinal
        CD = struct('u', 0.104,...
                    'alpha', 0.30,...
                    'deltae', 0,...
                    'ih', 0)
                
        CL = struct('u', 0.40,...
                    'alpha', 5.84,...
                    'alphadot', 2.2,...
                    'q', 4.7,...
                    'deltae', 0.46,...
                    'ih', 0.94)
                
        CT = struct('u', -0.07,...
                    'alpha', 0)
        
        Cm = struct('u', 0.050,...
                    'Tu', -0.003,...
                    'alpha', -0.64,...
                    'alphadot', -6.7,...
                    'q', -15.5,...
                    'T', 0,...
                    'deltae', -1.24,...
                    'ih', -2.5)
                
        % Lateral-directional
        CY = struct('beta', -0.730,...
                    'p', 0,...
                    'r', 0.40,...
                    'deltaa', 0,...
                    'deltar', -0.140)
                
        Cl = struct('beta', -0.110,...
                    'p', -0.450,...
                    'r', 0.160,...
                    'deltaa', 0.178,...
                    'deltar', -0.019)
                
        Cn = struct('beta', 0.127,...
                    'p', -0.008,...
                    'Tbeta', 0,...
                    'r', -0.200,...
                    'deltaa', -0.020,...
                    'deltar', 0.074)
                
    end
end

